using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GSearch
{
    public static class Constants
    {
        public const string GOOGLE_XML_URL = "http://google.com/complete/search?output=toolbar&q={0}&hl={1}"; // Head of the query URL

        // Languages
        public struct Languages
        {
            public const String Afrikaans = "af";
            public const String Akan = "ak";
            public const String Albanian = "sq";
            public const String Amharic = "am";
            public const String Arabic = "ar";
            public const String Armenian = "hy";
            public const String Azerbaijani = "az";
            public const String Basque = "eu";
            public const String Belarusian = "be";
            public const String Bemba = "bem";
            public const String Bengali = "bn";
            public const String Bihari = "bh";
            public const String Bork = "xx-bork";
            public const String Bosnian = "bs";
            public const String Breton = "br";
            public const String Bulgarian = "bg";
            public const String Cambodian = "km";
            public const String Catalan = "ca";
            public const String Cherokee = "chr";
            public const String Chichewa = "ny";
            public const String Chinese_Simplified = "zh-CN";
            public const String Chinese_Traditional = "zh-TW";
            public const String Corsican = "co";
            public const String Croatian = "hr";
            public const String Czech = "cs";
            public const String Danish = "da";
            public const String Dutch = "nl";
            public const String Elmer_Fudd = "xx-elmer";
            public const String English = "en";
            public const String Esperanto = "eo";
            public const String Estonian = "et";
            public const String Ewe = "ee";
            public const String Faroese = "fo";
            public const String Filipino = "tl";
            public const String Finnish = "fi";
            public const String French = "fr";
            public const String Frisian = "fy";
            public const String Ga = "gaa";
            public const String Galician = "gl";
            public const String Georgian = "ka";
            public const String German = "de";
            public const String Greek = "el";
            public const String Guarani = "gn";
            public const String Gujarati = "gu";
            public const String Hacker = "xx-hacker";
            public const String Haitian_Creole = "ht";
            public const String Hausa = "ha";
            public const String Hawaiian = "haw";
            public const String Hebrew = "iw";
            public const String Hindi = "hi";
            public const String Hungarian = "hu";
            public const String Icelandic = "is";
            public const String Igbo = "ig";
            public const String Indonesian = "id";
            public const String Interlingua = "ia";
            public const String Irish = "ga";
            public const String Italian = "it";
            public const String Japanese = "ja";
            public const String Javanese = "jw";
            public const String Kannada = "kn";
            public const String Kazakh = "kk";
            public const String Kinyarwanda = "rw";
            public const String Kirundi = "rn";
            public const String Klingon = "xx-klingon";
            public const String Kongo = "kg";
            public const String Korean = "ko";
            public const String Krio_Sierr_Leone = "kri";
            public const String Kurdish = "ku";
            public const String Kurdish_Sorani = "ckb";
            public const String Kyrgyz = "ky";
            public const String Laothian = "lo";
            public const String Latin = "la";
            public const String Latvian = "lv";
            public const String Lingala = "ln";
            public const String Lithuanian = "lt";
            public const String Lozi = "loz";
            public const String Luganda = "lg";
            public const String Luo = "ach";
            public const String Macedonian = "mk";
            public const String Malagasy = "mg";
            public const String Malay = "ms";
            public const String Malayalam = "ml";
            public const String Maltese = "mt";
            public const String Maori = "mi";
            public const String Marathi = "mr";
            public const String Mauritian_Creole = "mfe";
            public const String Moldavian = "mo";
            public const String Mongolian = "mn";
            public const String Montenegrin = "sr-ME";
            public const String Nepali = "ne";
            public const String Nigerian_Pidgin = "pcm";
            public const String Northern_Sotho = "nso";
            public const String Norwegian = "no";
            public const String Norwegian_Nynorsk = "nn";
            public const String Occitan = "oc";
            public const String Oriya = "or";
            public const String Oromo = "om";
            public const String Pashto = "ps";
            public const String Persian = "fa";
            public const String Pirate = "xx-pirate";
            public const String Polish = "pl";
            public const String Portuguese_Brazil = "pt-BR";
            public const String Portuguese_Portugal = "pt-PT";
            public const String Punjabi = "pa";
            public const String Quechua = "qu";
            public const String Romanian = "ro";
            public const String Romansh = "rm";
            public const String Runyakitara = "nyn";
            public const String Russian = "ru";
            public const String Scots_Gaelic = "gd";
            public const String Serbian = "sr";
            public const String Serbo_Croatian = "sh";
            public const String Sesotho = "st";
            public const String Setswana = "tn";
            public const String Seychellois_Creole = "crs";
            public const String Shona = "sn";
            public const String Sindhi = "sd";
            public const String Sinhalese = "si";
            public const String Slovak = "sk";
            public const String Slovenian = "sl";
            public const String Somali = "so";
            public const String Spanish = "es";
            public const String Spanish_Latin_American = "es-419";
            public const String Sundanese = "su";
            public const String Swahili = "sw";
            public const String Swedish = "sv";
            public const String Tajik = "tg";
            public const String Tamil = "ta";
            public const String Tatar = "tt";
            public const String Telugu = "te";
            public const String Thai = "th";
            public const String Tigrinya = "ti";
            public const String Tonga = "to";
            public const String Tshiluba = "lua";
            public const String Tumbuka = "tum";
            public const String Turkish = "tr";
            public const String Turkmen = "tk";
            public const String Twi = "tw";
            public const String Uighur = "ug";
            public const String Ukrainian = "uk";
            public const String Urdu = "ur";
            public const String Uzbek = "uz";
            public const String Vietnamese = "vi";
            public const String Welsh = "cy";
            public const String Wolof = "wo";
            public const String Xhosa = "xh";
            public const String Yiddish = "yi";
            public const String Yoruba = "yo";
            public const String Zulu = "zu";
        }
    }
}
