using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GSearch
{
    public static class Constants
    {
        public static const string GOOGLE_XML_URL = "http://google.com/complete/search?output=toolbar&q={0}&hl=en-US"; // Head of the query URL

        // Languages
        public static enum LANGUAGES
        {
            Afrikaans = "af",
            Akan = "ak",
            Albanian = "sq",
            Amharic = "am",
            Arabic = "ar",
            Armenian = "hy",
            Azerbaijani = "az",
            Basque = "eu",
            Belarusian = "be",
            Bemba = "bem",
            Bengali = "bn",
            Bihari = "bh",
            Bork = "xx-bork",
            Bosnian = "bs",
            Breton = "br",
            Bulgarian = "bg",
            Cambodian = "km",
            Catalan = "ca",
            Cherokee = "chr",
            Chichewa = "ny",
            Chinese_Simplified = "zh-CN",
            Chinese_Traditional = "zh-TW",
            Corsican = "co",
            Croatian = "hr",
            Czech = "cs",
            Danish = "da",
            Dutch = "nl",
            Elmer_Fudd = "xx-elmer",
            English = "en",
            Esperanto = "eo",
            Estonian = "et",
            Ewe = "ee",
            Faroese = "fo",
            Filipino = "tl",
            Finnish = "fi",
            French = "fr",
            Frisian = "fy",
            Ga = "gaa",
            Galician = "gl",
            Georgian = "ka",
            German = "de",
            Greek = "el",
            Guarani = "gn",
            Gujarati = "gu",
            Hacker = "xx-hacker",
            Haitian_Creole = "ht",
            Hausa = "ha",
            Hawaiian = "haw",
            Hebrew = "iw",
            Hindi = "hi",
            Hungarian = "hu",
            Icelandic = "is",
            Igbo = "ig",
            Indonesian = "id",
            Interlingua = "ia",
            Irish = "ga",
            Italian = "it",
            Japanese = "ja",
            Javanese = "jw",
            Kannada = "kn",
            Kazakh = "kk",
            Kinyarwanda = "rw",
            Kirundi = "rn",
            Klingon = "xx-klingon",
            Kongo = "kg",
            Korean = "ko",
            Krio_Sierr_Leone = "kri",
            Kurdish = "ku",
            Kurdish_Sorani = "ckb",
            Kyrgyz = "ky",
            Laothian = "lo",
            Latin = "la",
            Latvian = "lv",
            Lingala = "ln",
            Lithuanian = "lt",
            Lozi = "loz",
            Luganda = "lg",
            Luo = "ach",
            Macedonian = "mk",
            Malagasy = "mg",
            Malay = "ms",
            Malayalam = "ml",
            Maltese = "mt",
            Maori = "mi",
            Marathi = "mr",
            Mauritian_Creole = "mfe",
            Moldavian = "mo",
            Mongolian = "mn",
            Montenegrin = "sr-ME",
            Nepali = "ne",
            Nigerian_Pidgin = "pcm",
            Northern_Sotho = "nso",
            Norwegian = "no",
            Norwegian_Nynorsk = "nn",
            Occitan = "oc",
            Oriya = "or",
            Oromo = "om",
            Pashto = "ps",
            Persian = "fa",
            Pirate = "xx-pirate",
            Polish = "pl",
            Portuguese_Brazil = "pt-BR",
            Portuguese_Portugal = "pt-PT",
            Punjabi = "pa",
            Quechua = "qu",
            Romanian = "ro",
            Romansh = "rm",
            Runyakitara = "nyn",
            Russian = "ru",
            Scots_Gaelic = "gd",
            Serbian = "sr",
            Serbo_Croatian = "sh",
            Sesotho = "st",
            Setswana = "tn",
            Seychellois_Creole = "crs",
            Shona = "sn",
            Sindhi = "sd",
            Sinhalese = "si",
            Slovak = "sk",
            Slovenian = "sl",
            Somali = "so",
            Spanish = "es",
            Spanish_Latin_American = "es-419",
            Sundanese = "su",
            Swahili = "sw",
            Swedish = "sv",
            Tajik = "tg",
            Tamil = "ta",
            Tatar = "tt",
            Telugu = "te",
            Thai = "th",
            Tigrinya = "ti",
            Tonga = "to",
            Tshiluba = "lua",
            Tumbuka = "tum",
            Turkish = "tr",
            Turkmen = "tk",
            Twi = "tw",
            Uighur = "ug",
            Ukrainian = "uk",
            Urdu = "ur",
            Uzbek = "uz",
            Vietnamese = "vi",
            Welsh = "cy",
            Wolof = "wo",
            Xhosa = "xh",
            Yiddish = "yi",
            Yoruba = "yo",
            Zulu = "zu"
        }
    }
}
